defaults: &defaults
  annotate: false
  debug:    false
  log:      false
  log_file: log/upload_detector.log

development:
  <<: *defaults
  deamonized: false
  input_file: "tmp/sftp_simple.log"

test:
  <<: *defaults
  deamonized: false
  input_file: null
  log_file: null

production:
  <<: *defaults
  deamonized: true
  #input_file: "/var/log/sftp.log"
  input_file: "tmp/sftp.log"
