defaults: &defaults
  annotate: false
  debug:    false
  logfile: "log/upload_detector.log"

development:
  <<: *defaults
  daemonize: false
  input_file: "tmp/sftp_simple.log"

test:
  <<: *defaults
  daemonize: false
  input_file: null
  log_file: null

production:
  <<: *defaults
  daemonize: true
  input_file: "/var/log/sftp.log"
  #input_file: "tmp/sftp.log"
