defaults: &defaults
  annotate: false
  debug:    false
  logfile: "log/upload_detector.log"
  pidfile: "."

development:
  <<: *defaults
  daemonize: false
  input_file: "tmp/sftp_simple.log"

test:
  <<: *defaults
  daemonize: false
  input_file: null
  log_file: null

production:
  <<: *defaults
  daemonize: true
  pidfile: "/tmp"
  input_file: "/var/log/sftp.log"
  #input_file: "tmp/sftp.log"

tonga:
  <<: *defaults
  daemonize: true
  logfile: "log/tonga_upload_detector.log"
  pidfile: "/srv/import/upload_detector/tmp"
  input_file: "/var/log/sftp.log"


